### ISSUE TITLE
Code for tabular data experiments in section 6.1

### ISSUE THREAD

**Issue by JulienSiems** [alanjeffares/joint-ensembles#1] opened 2023-12-26 10:38 UTC
Hey!

Thank you for providing the code for the main experiments of your very interesting paper!
I was wondering whether you could add the code to reproduce the tabular data experiments in section 6.1?

Best, 
Julien

**Comment by alanjeffares** [comment] 2024-01-02 13:25
Hey Julien,

Thanks for checking out this project! 

Unfortunately, the code for the Bayesian Optimization piece was part of another project that was not carried forward into this new repository. The original project was aimed at improving joint training and these experiments were part of an early commit in that repo that were intended to be a baseline that we would try and improve on. 

However, they should be relatively easy to reproduce if they are useful to your work. The data and preprocessing scripts were taken from my previous project [TANGOS](https://github.com/alanjeffares/TANGOS) which does have all the code available (the only minor change is that we use the full data rather than just the first 1000 samples as that project was focused on the low data regime). Then we simply applied [W&B](https://wandb.ai/site) BayesOpt with the hyperparameters described in our main text.

I apologize that this piece is not available - I'm being more careful with future projects to ensure that all code is maintained such that it can be released in full.

Best wishes,
Alan

**Closed as completed** 2024-01-11 17:44 UTC
